---

### Ansible playbook for immutable KOps in multi-account / region combos
### Contributors : Andrew J Krug @andrewkrug irc: andrew
### This is licensed under the Mozilla Public License 2.0

- name: delete a stack
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
      AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
      STAGE: "{{ lookup('env', 'STAGE') }}"

  tasks:
    ### KOps requires we detach our custom policies prior to cluster teardown.
    - name: remove policy from role
      iam_policy:
        region: "{{AWS_REGION}}"
        iam_type: role
        iam_name: nodes.{{clustername}}
        policy_name: nodes.{{clustername}}
        state: absent

    ### KOps requires we detach our custom policies prior to cluster teardown.
    - name: remove policy from role
      iam_policy:
        region: "{{AWS_REGION}}"
        iam_type: role
        iam_name: masters.{{clustername}}
        policy_name: masters.{{clustername}}
        state: absent

    ### KOps requires we detach our custom policies prior to cluster teardown.
    - name: remove policy from role
      iam_policy:
        region: "{{AWS_REGION}}"
        iam_type: role
        iam_name: nodes.{{clustername}}
        policy_name: assumable-roles
        state: absent

    ### Add a policy to the node role that allows ssm
    - name: update node role with ssm permissions
      iam_policy:
        region: "{{AWS_REGION}}"
        iam_type: role
        iam_name: nodes.{{clustername}}
        policy_name: ssm
        state: absent

    ### Actually let KOps remove the cluster
    - name: delete the cluster
      shell: kops delete cluster {{clustername}} --yes
      args:
        chdir: ../kops-configs/
